Parking reservation
rodriguezbruno/parkingProject pull request #3
Opened 2021-07-05 15:48 UTC by rodriguezbruno

2021-07-05 18:11 UTC, carlos-navas-globant requested changes

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".activities.MenuActivity"></activity>
FYI
you can close it with a `/>` instead of `</activity>` as any other XML

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/fragments/ReservationFragment.java
> +
extra spaces

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +    public void onFrom() {
try to imagine someone looking at your code, probably he would not understand what are you referring to. You can change it to somthing like `onStartDateTimePressed`

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +    public void onTo() {
same as above

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +    public boolean onSchedule() {
this method is kind of strange, it returns a boolean but the name is confusing, let's review it in our call please

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if (this.validateSecurityCode(securityCode) && this.validateParkingLot(parkingNumber) && this.validateReservationDates(startDate, endDate)) {
there is no need to explicitly say `this.validate...`. You can directly call validateSecurityCode()

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +            boolean addedReserve = reservationModel.addReservation(reservation);
`boolean reservationAdded` sounds better I believe

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +
extra space

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    public void startDateTimeDialog() {
`showStartDateTimeDialog`?

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    public void endDateTimeDialog() {
`showEndDateTimeDialog`?

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/utils/DateTimeUtils.java
> +public class DateTimeUtils {
are you using this? if not, you can delete this class

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/utils/Picker.java
> +    public void showDateTimeDialog(EditText date_time) {
Java naming convention should be `dateTime`

2021-07-05 18:11 UTC, carlos-navas-globant commented on app/src/main/java/com/example/parkingproyect/utils/Picker.java
> +    public Picker(EditText date_time) {
Java naming convention should be `dateTime`

2021-07-12 21:10 UTC, imachadoglobant requested changes
Please check my comments.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/fragments/ReservationFragment.java
> +    }
Please define interfaces at the top of the class, before any member definition.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/fragments/ReservationFragment.java
> +        if(getArguments() != null) {
Fix format.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/fragments/ReservationFragment.java
> +                delegate.onReservationFragmentButtonClicked(presenter.getParkingWithReservations());
Check if delegate is not null or the app could crash because of NPE.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +    }
There is no need to define a method for a single line of code.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +            ArrayList<Reservation> reservations = getReservationsList();
There is no need to define a variable for this.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +            valid = true;
Do `return true;` here to avoid the else block.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +                }
You can simplify this by doing:
```
if (reservation.getParkingLot() == reservationList.getParkingLot() &&
  reservation.getStartDateTime() < reservationList.getEndDateTime()) {
    return false;
}
```

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +        boolean valid = false;
This variable definition can be omitted.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/model/ReservationModel.java
> +    public int getParkingNumber(String parkingNumberString){
Fix format.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +            boolean reservationAdded = reservationModel.addReservation(reservation);
This variable definition can be omitted.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +                reservationView.showSuccessMessageReservationAdded();
Shouldn't you do `return true;` here?

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if(TextUtils.isEmpty(securityCode)){
Fix format. Using TextUtils in presenters makes them harder to unit test. You can replace TextUtils.isEmpty by doing !code.isEmpty() since TextView.getText().toString() shouldn't return null.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if (securityCode.length() >= 3 && securityCode.length() <= 5) {
If you invert this condition, you can avoid having an else block.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if(parkingNumber <= 0){
Fix format.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if (parkingNumber <= reservationModel.getParking().getParkingSize()) {
Invert condition to avoid the else block.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/presenter/ReservationPresenter.java
> +        if (startDate < endDate && startDate >= new Date().getTime()) {
Invert condition.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ParkingView.java
> +    private final Context context;
Avoid hard references to context, as they may produce memory leaks. Remove this attribute.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    private final Context context;
Avoid hard references to context, as they may produce memory leaks. Remove this attribute.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +        if (startDatePicker != null) {
This check is not needed, startDatePicker is always initialized.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    public Date getEndDate() {
This check is not needed, startDatePicker is always initialized.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    }
Maybe you could avoid repeated code by defining a private method.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/utils/Picker.java
> +                        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yy-MM-dd HH:mm");
Define date format as constant.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/activity_menu.xml
> +        app:layout_constraintTop_toBottomOf="@+id/button_parking_add_reservation"
Remove "+".

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/activity_menu.xml
> +        app:layout_constraintBottom_toTopOf="@+id/button_parking_automatic_release" />
Remove "+".

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/activity_menu.xml
> +    app:layout_constraintBottom_toBottomOf="parent"/>
Fix format.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/fragment_reservation.xml
> +            app:layout_constraintTop_toBottomOf="@+id/start_date_time"
Remove "+".

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/fragment_reservation.xml
> +
Remove extra empty line.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/main/res/layout/fragment_reservation.xml
> +
Remove extra empty line.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +public class ParkingReservationTest {
Use the same name as the class you're testing, rename to "ReservationPresenterTest".

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +@RunWith(RobolectricTestRunner.class)
If you don't use TextUtils, you don't need Robolectric and your tests will run faster.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        doReturn(true).when(spyPresenter).validateReservationDates(startDate.getTime(), endDate.getTime());
Can you do `when(spyPresenter).validateSecurityCode("A123").thenReturn(true)` and so on?

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        Assert.assertTrue(presenter.validateSecurityCode("A123"));
Also verify no errors are shown.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +    public void validate_securityCode_outOfRange_toShort() {
Typo in "tooShort".

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        Assert.assertTrue(presenter.validateParkingLot(15));
Also verify no errors are shown.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        Assert.assertTrue(presenter.validateReservationDates(startDate.getTime(), endDate.getTime()));
Also verify no errors are shown.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +    public void validate_parkingDates_startDate_less_today() {
Rename to validateReservationDates_startDateBeforeToday_false and so on.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +    public void validate_show_start_date_time() {
There are several naming conventions for tests, but our proposal is to use: MethodName_StateUnderTest_ExpectedBehavior.
For example, this should be renamed to onStartDateTimePressed_ showEndDateTimeInput.
Apply the same convention for all tests.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +    public void validate_addReservation_success() {
Rename this to onAddNewReservationPressed_success

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +    public void validate_get_parking_with_list_of_reservations() {
Here you could start defining a local variable `int parkingSize = 20;`

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        when(model.getParking()).thenReturn(new Parking(20));
Use parkingSize variable here.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ParkingReservationTest.java
> +        Assert.assertEquals(new Parking(20).getParkingSize(), presenter.getParkingWithReservations().getParkingSize());
And here do `assertEquals(parkingSize, presenter.getParkingWithReservations().getParkingSize());`

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/mvp/model/ReservationModelTest.java
> +    ReservationModel model;
Define attribute access modifier.

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/mvp/model/ReservationModelTest.java
> +        Assert.assertEquals(new Parking(20).getParkingSize(), model.getParking().getParkingSize());
Do this instead: `assertEquals(20, model.getParking().getParkingSize());`

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/mvp/model/ReservationModelTest.java
> +        Assert.assertEquals(new Parking(20).getReservationsList(), model.getReservationsList());
Do this instead: `assertEquals(new ArrayList(), model.getReservationList());`

2021-07-12 21:10 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/mvp/model/ReservationModelTest.java
> +        Assert.assertTrue(model.addReservation(new Reservation()));
Fill the reservation instance with valid data.

2021-07-16 20:18 UTC, imachadoglobant requested changes

2021-07-16 20:18 UTC, imachadoglobant commented on app/src/main/java/com/example/parkingproyect/mvp/view/ReservationView.java
> +    }
Objects.requireNonNull() will throw NullPointerException if context is null, and that will make your app crash.

2021-07-16 20:18 UTC, imachadoglobant commented on app/src/test/java/com/example/parkingproyect/ReservationPresenterTest.java
> +        when(model.getParking()).thenReturn(new Parking(20));
Use parkingSize here instead of "20"

2021-07-16 20:46 UTC, imachadoglobant approved these changes

2021-07-19 14:00 UTC, carlos-navas-globant approved these changes

2021-07-19 18:05 UTC, merged